components:
    schemas:
        CTCollection:
            # @review
            description:
                Represents a set of changes tracked for a publication.
            properties:
                actions:
                    additionalProperties:
                        additionalProperties:
                            type: string
                        type: object
                    readOnly: true
                    type: object
                dateCreated:
                    description:
                        The publication's creation date.
                    format: date-time
                    readOnly: true
                    type: string
                dateModified:
                    description:
                        The last time any of the publication's fields were changed.
                    format: date-time
                    readOnly: true
                    type: string
                dateScheduled:
                    description:
                        The date that the publication will be published.
                    format: date-time
                    readOnly: true
                    type: string
                description:
                    type: string
                id:
                    format: int64
                    readOnly: true
                    type: integer
                name:
                    type: string
                ownerName:
                    description:
                        The publication's creator.
                    readOnly: true
                    type: string
                status:
                    $ref: "#/components/schemas/Status"
                    readOnly: true
            type: object
        CTEntry:
            properties:
                actions:
                    additionalProperties:
                        additionalProperties:
                            type: string
                        type: object
                    readOnly: true
                    type: object
                changeType:
                    format: int32
                    readOnly: true
                    type: integer
                ctCollectionId:
                    format: int64
                    readOnly: true
                    type: integer
                dateCreated:
                    format: date-time
                    readOnly: true
                    type: string
                dateModified:
                    format: date-time
                    readOnly: true
                    type: string
                hideable:
                    readOnly: true
                    type: boolean
                id:
                    format: int64
                    readOnly: true
                    type: integer
                modelClassNameId:
                    format: int64
                    readOnly: true
                    type: integer
                modelClassPK:
                    format: int64
                    readOnly: true
                    type: integer
                ownerName:
                    readOnly: true
                    type: string
                siteName:
                    readOnly: true
                    type: string
                status:
                    $ref: "#/components/schemas/Status"
                    readOnly: true
                title:
                    readOnly: true
                    type: string
                typeName:
                    readOnly: true
                    type: string
            type: object
        Status:
            properties:
                code:
                    format: int32
                    type: integer
                label:
                    type: string
                label_i18n:
                    type: string
            type: object
info:
    description:
        "A Java client JAR is available for use with the group ID 'com.liferay', artifact ID
        'com.liferay.change.tracking.rest.client', and version '1.0.0'."
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: ""
    version: v1.0
openapi: 3.0.1
paths:
    "/ct-collections":
        get:
            operationId: getCTCollectionsPage
            parameters:
                - in: query
                  name: status
                  schema:
                      items:
                          type: integer
                      type: array
                - in: query
                  name: page
                  schema:
                      type: integer
                - in: query
                  name: pageSize
                  schema:
                      type: integer
                - in: query
                  name: search
                  schema:
                      type: string
                - in: query
                  name: sort
                  schema:
                      type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/CTCollection"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/CTCollection"
                                type: array
            tags: ["CTCollection"]
        post:
            operationId: postCTCollection
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/CTCollection"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/CTCollection"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/CTCollection"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/CTCollection"
            tags: ["CTCollection"]
    "/ct-collections/{ctCollectionId}":
        delete:
            operationId: deleteCTCollection
            parameters:
                - in: path
                  name: ctCollectionId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                204:
                    content:
                        application/json: {}
                        application/xml: {}
            tags: ["CTCollection"]
        get:
            operationId: getCTCollection
            parameters:
                - in: path
                  name: ctCollectionId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/CTCollection"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/CTCollection"
            tags: ["CTCollection"]
        patch:
            operationId: patchCTCollection
            parameters:
                - in: path
                  name: ctCollectionId
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/CTCollection"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/CTCollection"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/CTCollection"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/CTCollection"
            tags: ["CTCollection"]
        put:
            operationId: putCTCollection
            parameters:
                - in: path
                  name: ctCollectionId
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/CTCollection"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/CTCollection"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/CTCollection"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/CTCollection"
            tags: ["CTCollection"]
    "/ct-collections/{ctCollectionId}/checkout":
        post:
            operationId: postCTCollectionCheckout
            parameters:
                - in: path
                  name: ctCollectionId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json: {}
                        application/xml: {}
            tags: ["CTCollection"]
    "/ct-collections/{ctCollectionId}/ct-entries":
        get:
            operationId: getCtCollectionCTEntriesPage
            parameters:
                - in: path
                  name: ctCollectionId
                  required: true
                  schema:
                      format: int64
                      type: integer
                - in: query
                  name: filter
                  schema:
                      type: string
                - in: query
                  name: page
                  schema:
                      type: integer
                - in: query
                  name: pageSize
                  schema:
                      type: integer
                - in: query
                  name: search
                  schema:
                      type: string
                - in: query
                  name: sort
                  schema:
                      type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/CTEntry"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/CTEntry"
                                type: array
            tags: ["CTEntry"]
    "/ct-collections/{ctCollectionId}/publish":
        post:
            operationId: postCTCollectionPublish
            parameters:
                - in: path
                  name: ctCollectionId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json: {}
                        application/xml: {}
            tags: ["CTCollection"]
    "/ct-collections/{ctCollectionId}/schedule-publish":
        post:
            operationId: postCTCollectionSchedulePublish
            parameters:
                - in: path
                  name: ctCollectionId
                  required: true
                  schema:
                      format: int64
                      type: integer
                - in: query
                  name: publishDate
                  required: false
                  schema:
                      format: date-time
                      type: string
            responses:
                200:
                    content:
                        application/json: {}
                        application/xml: {}
            tags: ["CTCollection"]
    "/ct-entries/{ctEntryId}":
        get:
            operationId: getCTEntry
            parameters:
                - in: path
                  name: ctEntryId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/CTEntry"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/CTEntry"
            tags: ["CTEntry"]